// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationMenu() {
  return window['go']['app']['App']['ApplicationMenu']();
}

export function CreateNewWire(arg1) {
  return window['go']['app']['App']['CreateNewWire'](arg1);
}

export function GetWireOtp(arg1) {
  return window['go']['app']['App']['GetWireOtp'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ListWires() {
  return window['go']['app']['App']['ListWires']();
}
