// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {wire} from '../models';

export function ApplicationMenu():Promise<menu.Menu>;

export function CreateNewWire(arg1:string):Promise<wire.Wire>;

export function Greet(arg1:string):Promise<string>;

export function ListWires():Promise<Array<wire.Wire>>;
